"""add_anonymous_chats_and_matchmaking

Revision ID: 5ce69359c136
Revises: 60b9e4673981
Create Date: 2025-11-16 00:55:22.941223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ce69359c136'
down_revision: Union[str, Sequence[str], None] = '60b9e4673981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_chats_user1_id'), 'anonymous_chats', ['user1_id'], unique=False)
    op.create_index(op.f('ix_anonymous_chats_user2_id'), 'anonymous_chats', ['user2_id'], unique=False)
    op.create_table('matchmaking_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_searching', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchmaking_queue_user_id'), 'matchmaking_queue', ['user_id'], unique=True)
    op.create_table('anonymous_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['anonymous_chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_messages_chat_id'), 'anonymous_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_anonymous_messages_sender_id'), 'anonymous_messages', ['sender_id'], unique=False)
    op.drop_constraint(op.f('psychological_profiles_user_id_key'), 'psychological_profiles', type_='unique')
    op.drop_index(op.f('ix_psychological_profiles_user_id'), table_name='psychological_profiles')
    op.create_index(op.f('ix_psychological_profiles_user_id'), 'psychological_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psychological_profiles_user_id'), table_name='psychological_profiles')
    op.create_index(op.f('ix_psychological_profiles_user_id'), 'psychological_profiles', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('psychological_profiles_user_id_key'), 'psychological_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_anonymous_messages_sender_id'), table_name='anonymous_messages')
    op.drop_index(op.f('ix_anonymous_messages_chat_id'), table_name='anonymous_messages')
    op.drop_table('anonymous_messages')
    op.drop_index(op.f('ix_matchmaking_queue_user_id'), table_name='matchmaking_queue')
    op.drop_table('matchmaking_queue')
    op.drop_index(op.f('ix_anonymous_chats_user2_id'), table_name='anonymous_chats')
    op.drop_index(op.f('ix_anonymous_chats_user1_id'), table_name='anonymous_chats')
    op.drop_table('anonymous_chats')
    # ### end Alembic commands ###
